cli tests - adding -t option to exit on failure

diff --git a/scripts/system-test/cli-system-test b/scripts/system-test/cli-system-test
--- a/scripts/system-test/cli-system-test
+++ b/scripts/system-test/cli-system-test
@@ -44,6 +44,7 @@ NO_BASE=0
 NO_CLEANUP=0
 RUN_DISABLED=0
 RAND_PREFIX=""
+TERMINATE=9999
 while [ $# -gt 0 ]; do
     case "$1" in
         "-h"|"--help")
@@ -58,6 +59,8 @@ while [ $# -gt 0 ]; do
             printf " -s, --shell     runs tests in the shell mode\n"
             printf " -p, --ping      checks whether the server is ready\n"
             printf " --rand-prefix   prefixes random hash with given value\n"
+            printf " -t, --termfirst terminate on the first error\n"
+            printf " --termn [N]     terminate on the n-th error\n"
             printf "\n"
             printf "Available tests:\n"
             printf " all\n"
@@ -89,6 +92,13 @@ while [ $# -gt 0 ]; do
         "--rand-prefix")
             shift
             RAND_PREFIX=$1
+            ;;
+        "-t"|"--termfirst")
+            TERMINATE=1
+            ;;
+        "--termn")
+            shift
+            TERMINATE=$1
             ;;
         "-s"|"--shell")
             SHELL_MODE=1
@@ -224,6 +234,7 @@ function test_cmd() {
             printf "%s\n" "$result"
         fi
         let failed_cnt+=1
+        let "TERMINATE=$TERMINATE - 1"
     else
         if [ $PRINT_ALL -eq 1 ]; then
             printf "%s\n\n" "$result"
@@ -233,6 +244,12 @@ function test_cmd() {
     fi
     log_test_result "$status" "$test_name" "$result"
     let test_cnt+=1
+    if [ $status -eq 0 -a $TERMINATE -le 0 ]; then
+        # immediate termination
+        echo "Failure, exiting:"
+        echo "$*"
+        exit 1
+    fi
 }
 
 
